# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(932, 600)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.login_btn = QtWidgets.QPushButton(self.tab)
        self.login_btn.setObjectName("login_btn")
        self.gridLayout_2.addWidget(self.login_btn, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 2, 1, 1)
        self.login_pass = QtWidgets.QLineEdit(self.tab)
        self.login_pass.setObjectName("login_pass")
        self.gridLayout_2.addWidget(self.login_pass, 4, 1, 1, 1)
        self.login_login = QtWidgets.QLineEdit(self.tab)
        self.login_login.setObjectName("login_login")
        self.gridLayout_2.addWidget(self.login_login, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.login_err = QtWidgets.QLabel(self.tab)
        self.login_err.setStyleSheet("color: rgb(255, 0, 0);")
        self.login_err.setText("")
        self.login_err.setAlignment(QtCore.Qt.AlignCenter)
        self.login_err.setObjectName("login_err")
        self.gridLayout_2.addWidget(self.login_err, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 5, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 7, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 1, 1, 1)
        self.reg_login = QtWidgets.QLineEdit(self.tab_2)
        self.reg_login.setObjectName("reg_login")
        self.gridLayout_4.addWidget(self.reg_login, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 1, 1, 1)
        self.register_pass = QtWidgets.QLineEdit(self.tab_2)
        self.register_pass.setObjectName("register_pass")
        self.gridLayout_4.addWidget(self.register_pass, 4, 1, 1, 1)
        self.register_btn = QtWidgets.QPushButton(self.tab_2)
        self.register_btn.setObjectName("register_btn")
        self.gridLayout_4.addWidget(self.register_btn, 5, 1, 1, 1)
        self.register_err = QtWidgets.QLabel(self.tab_2)
        self.register_err.setStyleSheet("color: rgb(255, 0, 0);")
        self.register_err.setText("")
        self.register_err.setAlignment(QtCore.Qt.AlignCenter)
        self.register_err.setObjectName("register_err")
        self.gridLayout_4.addWidget(self.register_err, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_btn.setText(_translate("Form", "Sign in"))
        self.label_2.setText(_translate("Form", "Password"))
        self.label.setText(_translate("Form", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab), _translate("Form", "Login"))
        self.label_6.setText(_translate("Form", "Login"))
        self.label_5.setText(_translate("Form", "Password"))
        self.register_btn.setText(_translate("Form", "Sign up"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_2), _translate("Form", "Register"))
